### ISSUE TITLE
训练报错：

### ISSUE THREAD

**Issue by world2025** [Levigty/EfficientNet-Pytorch#1]
你好，感谢你的开源，我在训练的时候报了一个错

**Comment by world2025** [comment]
IndexError: dimension specified as 0 but tensor has no dimensions，不知道你有没有遇到这个错

**Comment by Levigty** [comment]
报错的位置在哪里呢？

**Comment by world2025** [comment]
Traceback (most recent call last):
  File "F:/BONC/vehicle/EfficientNet-Pytorch-master/efficientnet_sample.py", line 188, in <module>
    train_loss, best_model_wts = train_model(model_ft, criterion, optimizer, exp_lr_scheduler, num_epochs=num_epochs)
  File "F:/BONC/vehicle/EfficientNet-Pytorch-master/efficientnet_sample.py", line 78, in train_model
    loss = criterion(outputs, labels)
  File "D:\python3.6\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\python3.6\lib\site-packages\torch\nn\modules\loss.py", line 942, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "D:\python3.6\lib\site-packages\torch\nn\functional.py", line 2056, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "D:\python3.6\lib\site-packages\torch\nn\functional.py", line 1867, in nll_loss
    if input.size(0) != target.size(0):

**Comment by world2025** [comment]
Epoch:0: loss:4.238
Epoch:0: loss:3.461
Epoch:0: loss:2.165
Epoch:0: loss:4.265
Epoch:0: loss:4.086
Epoch:0: loss:2.209
Epoch:0: loss:3.180
Epoch:0: loss:2.533
Epoch:0: loss:3.179
Epoch:0: loss:3.874
Epoch:0: loss:3.066
Epoch:0: loss:3.183
Epoch:0: loss:4.060
Epoch:0: loss:2.909
Epoch:0: loss:3.872
Epoch:0: loss:3.967
Epoch:0: loss:3.723
Epoch:0: loss:2.886
Epoch:0: loss:4.056
Epoch:0: loss:3.559
Epoch:0: loss:1.769
Epoch:0: loss:3.386
Epoch:0: loss:2.318
Epoch:0: loss:4.217
Epoch:0: loss:4.093
Epoch:0: loss:2.699
训练完第一个epoch后报错

**Comment by Levigty** [comment]
你截图的不太全，所以最终报错是定位到loss = criterion(outputs, labels)？不过不可能啊你训练都开始了啊，你看看报错最终在哪里

**Comment by world2025** [comment]
我是全部复制了

**Comment by world2025** [comment]
所以我也很纳闷

**Comment by world2025** [comment]
可能是batch_size处理问题，可能不同数据集得设置合适的batch_size, 我改了batch_size又可以跑通了

**Comment by Levigty** [comment]
好的嘻嘻，感觉都跑起来了应该也不会有大问题，祝好运~
